import { GithubIssueModel } from './github-issue.model';

/** Code is generated by VSCode extionsion "Paste JSON as Code"
 * URL: https://marketplace.visualstudio.com/items?itemName=quicktype.quicktype
*/
export interface GithubSearchResponseModel {
    total_count:        number;
    incomplete_results: boolean;
    items:              GithubIssueModel[];
}
